### ISSUE TITLE
[Error] 看板娘无法加载贴图，对话框与工具栏正常

### ISSUE THREAD

**Issue by Philogag** [Harry-zklcdc/OJ#4]
![image](https://user-images.githubusercontent.com/44018455/65948262-7dd19980-e46c-11e9-83d3-85a098089dc8.png)

![image](https://user-images.githubusercontent.com/44018455/65948642-3e577d00-e46d-11e9-9560-5b3ca99e5de2.png)
![image](https://user-images.githubusercontent.com/44018455/65948690-4fa08980-e46d-11e9-8c68-9042ef021a4d.png)

### 系统配置
使用微调的 稳健oj docker-compose配置（只修改了测评机部分，应该没影响）
使用了内网穿透工具[nps](https://github.com/cnlh/nps)，只穿了http，没加https

**Comment by Harry-zklcdc** [comment]
去看看这个，在 date/forum 文件夹里面建一个 model 文件夹，将下载下来的 model 放到里面，默认是血小板的 model
live2d 的 model ：[https://github.com/Harry-zklcdc/live2d_models](https://github.com/Harry-zklcdc/live2d_models)
要配合我的 docker-compose.yml 使用，因为live2d 的后端是PHP，要开一个新的容器。而且我在 OJ 的后端做了反向代理。具体看这里：[https://github.com/Harry-zklcdc/OnlineJudgeDeploy](https://github.com/Harry-zklcdc/OnlineJudgeDeploy)
modle文件夹规范：[https://github.com/Harry-zklcdc/OnlineJudgeDeploy/tree/2.0/data/forum/api/live2d](https://github.com/Harry-zklcdc/OnlineJudgeDeploy/tree/2.0/data/forum/api/live2d)

**Comment by Harry-zklcdc** [comment]
我也有点忘了，等我回学校在看一下那个目录结构
